name: CI

on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{matrix.rust}}
      - run: cargo check

  solution:
    name: Project ${{matrix.project}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project: [builder, debug, seq, sorted, bitfield]
    env:
      GIT_COMMITTER_EMAIL: proc-macro-workshop@dtolnay.github.io
      GIT_COMMITTER_NAME: proc-macro-workshop CI
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: git fetch origin --unshallow refs/solution/${{matrix.project}} HEAD
      - run: git rebase HEAD FETCH_HEAD
      - run: cargo test
        working-directory: ${{matrix.project}}

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/install@cargo-outdated
      - run: cargo outdated --workspace --exit-code 1
